apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-mrshaik-container
        image: mrshaik786/healthcare-app
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app

  type: NodePort
  ports:
  - nodePort: 31003   
    port: 8083
    targetPort: 8083
